spring:
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false
    password: changeme
    username: postgres
    url: jdbc:postgresql://localhost:5433/test?useSSL=false
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #show_sql: true
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:liquibase/schema/public/schema-public-master.xml
    default-schema: public

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false